services:
  trafego-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"  # Use uma porta disponível
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
