name: action/integration

on:
  push:
    branches:
      - action/integration

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Setup Java SDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: user/repo:latest

      - name: Run Maven Build
        run: mvn clean package

      - name: Run Unit Tests
        run: mvn test

