name: action/integration

on:
  push:
    branches:
      - action/integration

jobs:
  build_and_test:
    runs-on: ubuntu-latest  # Use ubuntu ou windows conforme sua preferência

    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Setup Java SDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean package

      - name: List files in target directory
        run: ls target  # Use 'ls' para listar em sistemas Linux ou 'dir' para Windows

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          push: false
          context: .
          file: Dockerfile
          tags: user/repo:latest
