name: Gerenciamento de Trafego CI

on:
  push:
    branches:
      - develop  # Ações acionadas ao fazer push na branch 'develop'
  pull_request:
    branches:
      - develop  # Ações acionadas ao abrir um pull request para a branch 'develop'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Verifica o repositório do GitHub
    - name: Checkout code
      uses: actions/checkout@v3

    # Configura o JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v3git 
      with:
        java-version: '17'
        distribution: 'temurin'

    # Configura o Maven cache para acelerar builds futuros
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Executa o comando Maven para construir o projeto
    - name: Build with Maven
      run: mvn clean install

    # Executa os testes do Maven
    - name: Run tests
      run: mvn test
